<?php

namespace Satisfactory\OperationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConcatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcatRepository extends EntityRepository
{
    
}
