<?php

namespace Satisfactory\OperationBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

/**
 * CorrespondanceRepository
 *
 * This class was generated by the ODM. Add your own custom
 * repository methods below.
 */
class CorrespondenceRepository extends DocumentRepository
{
    /**
     * @param User entity $client
     * @param string $expression
     *
     * @return array
     */
    public function searchByClient($client, $expression) 
    {
        
        $qb = $this->createQueryBuilder()
                ->field('client')
                ->equals(new \MongoRegex('/.*'.$client.'.*/i'))
                ->field('name')
                ->equals(new \MongoRegex('/.*'.$expression.'.*/i'));
        
        return $qb->getQuery()->execute();
    }
    
    /**
     * @param string $expression
     *
     * @return array
     */
    public function findWithSearch($expression) 
    {
        
        $qb = $this->createQueryBuilder()
                ->field('name')
                ->equals(new \MongoRegex('/.*'.$expression.'.*/i'));

        return $qb->getQuery()->execute();
    }
    
    /**
     * @param Correspondence id $correspondenceId 
     *
     * @return Correspondence entity
     */
    public function findByIndex($correspondenceId) 
    {
        $qb = $this->createQueryBuilder()
                ->field('index')
                ->equals($correspondenceId);
        
        return $qb->getQuery()->getSingleResult();
    } 
}
