<?php

namespace Satisfactory\OperationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FilteringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilteringRepository extends EntityRepository
{
    /**
     * @param User entity $client
     * @param string $expression
     *
     * @return array
     */
    public function findBySearch($client, $expression) 
    {
        $qb = $this->createQueryBuilder('f')
                ->select('f')
                ->where('f.name LIKE :expression')
                ->setParameter('expression', '%' . $expression . '%');
        
        if($client != 'all')
        {
          $qb->andWhere('f.client = :client')
             ->setParameter('client', $client);
        }  
        
        return $qb->getQuery()->getResult();
    }
}
