<?php

namespace Satisfactory\OperationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RejectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RejectRepository extends EntityRepository
{
    
    /**
     * @param User entity $client
     * @param string $type
     * @param string $expression
     *
     * @return array
     */
    public function findBySearch($client, $type, $expression) 
    {
        $qb = $this->createQueryBuilder('r')
                ->select('r')
                ->where('r.ruleName LIKE :expression')
                ->setParameter('expression', '%' . $expression . '%');
        
        if($client != 'all')
        {
          $qb->andWhere('r.client = :client')
             ->setParameter('client', $client);
        }
        
        if($type != 'all')
        {
          $qb->andWhere('r.type = :type')
             ->setParameter('type', $type);
        }  
        
        return $qb->getQuery()->getResult();
    }
    
     /**
     * @param $limit
     * @param $offset
     * @param $client
     *
     * @return array
     */
    public function paginatorQuery($limit, $offset = 0, $input, $client, $order, $orderType, $type)
    {
        
        $qb = $this->createQueryBuilder('d');

        if ($input) {
            $qb->andWhere('d.ruleName LIKE :name')
                    ->setParameter('name', '%' . $input . '%');
        }
        
        if ($client <> 'all') {
            $qb->andWhere('d.client =:client')
                    ->setParameter('client', $client);
        }
        
        if ($type <> 'all') {
            $qb->andWhere('d.type =:type')
                    ->setParameter('type', $type);
        }

        if ($limit) {
            $qb->setFirstResult($offset)
                    ->setMaxResults($limit);
        }
        
        $qb->orderBy('d.'.$order, $orderType);

        return $qb->getQuery()->getResult();
    }
    
    /**
     * @param $offset
     * @param $client
     *
     * @return array
     */
    public function paginatorQueryLimitOff( $offset = 0, $input, $client, $order, $orderType, $type)
    {
        
        $qb = $this->createQueryBuilder('d');

        if ($input) {
            $qb->andWhere('d.ruleName LIKE :name')
                    ->setParameter('name', '%' . $input . '%');
        }
        
        if ($client <> 'all') {
            $qb->andWhere('d.client =:client')
                    ->setParameter('client', $client);
        }
        
        if ($type <> 'all') {
            $qb->andWhere('d.type =:type')
                    ->setParameter('type', $type);
        }
        
        $qb->orderBy('d.'.$order, $orderType);

        return $qb->getQuery()->getResult();
    }
}
