<?php

namespace Satisfactory\SettingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgencySegmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgencySegmentRepository extends EntityRepository
{
}
