<?php

namespace Satisfactory\SettingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgencyQuestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgencyQuestRepository extends EntityRepository
{
}
