<?php

namespace Satisfactory\SettingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupAgencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupAgencyRepository extends EntityRepository
{
}
