<?php

namespace Satisfactory\CronBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CronexecutionOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronexecutionOperationRepository extends EntityRepository
{
    
    
}
