<?php

namespace Satisfactory\CronBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ManualexecutedealingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManualexecutedealingRepository extends EntityRepository
{
}
