<?php

namespace Satisfactory\CronBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

/**
 * ParamGroupesRepository
 *
 * This class was generated by the ODM. Add your own custom
 * repository methods below.
 */
class ParamGroupesRepository extends DocumentRepository
{
    
    /**
     * @return array ParamGroupes 
     *
     * @param User Id  $userId
     */
    public function findByUser($userId) 
    {
        $query = $this->createQueryBuilder('ParamGroupes')
                    ->distinct('groupId')
                    ->field('userId')->equals($userId);
        
        return $query->getQuery()->execute()->toArray();
    } 
    
}
